2025-04-16T15:02:29.094657+0300 INFO Metrics updated successfully
2025-04-16T15:07:29.135227+0300 INFO Metrics updated successfully
2025-04-16T15:12:29.160338+0300 INFO Metrics updated successfully
2025-04-16T15:17:29.188009+0300 INFO Metrics updated successfully
2025-04-16T15:22:29.205097+0300 INFO Metrics updated successfully
2025-04-16T15:27:29.233773+0300 INFO Metrics updated successfully
2025-04-16T16:44:35.814049+0300 INFO Metrics updated successfully
2025-04-16T16:50:59.380109+0300 ERROR Metrics update error: [Errno 111] Connection refused
2025-04-16T16:50:59.380874+0300 ERROR Failed to update metrics: [Errno 111] Connection refused
2025-04-16T16:55:28.754246+0300 INFO Metrics updated successfully
2025-04-16T17:00:28.764768+0300 INFO Metrics updated successfully
2025-04-16T17:05:28.799567+0300 INFO Metrics updated successfully
2025-04-16T17:10:28.825875+0300 INFO Metrics updated successfully
2025-04-16T17:15:28.833933+0300 INFO Metrics updated successfully
2025-04-16T17:20:28.862362+0300 INFO Metrics updated successfully
2025-04-16T17:25:28.871506+0300 INFO Metrics updated successfully
2025-04-16T17:28:51.010047+0300 INFO Metrics updated successfully
2025-04-16T17:30:14.316428+0300 INFO Metrics updated successfully
2025-04-16T17:30:47.988654+0300 INFO Metrics updated successfully
2025-04-16T17:31:44.352150+0300 INFO Metrics updated successfully
2025-04-16T17:32:59.343162+0300 INFO Metrics updated successfully
2025-04-16T17:37:59.351002+0300 INFO Metrics updated successfully
2025-04-16T17:42:59.377189+0300 INFO Metrics updated successfully
2025-04-16T17:47:59.386511+0300 INFO Metrics updated successfully
2025-04-16T17:51:50.385644+0300 INFO Metrics updated successfully
2025-04-16T17:52:23.772979+0300 INFO Metrics updated successfully
2025-04-16T17:57:23.781083+0300 INFO Metrics updated successfully
2025-04-16T18:02:23.788647+0300 INFO Metrics updated successfully
2025-04-16T18:07:23.797227+0300 INFO Metrics updated successfully
2025-04-16T18:12:23.824970+0300 INFO Metrics updated successfully
2025-04-16T18:14:14.623601+0300 INFO Metrics updated successfully
2025-04-16T18:19:14.633856+0300 INFO Metrics updated successfully
2025-04-16T18:24:14.641469+0300 INFO Metrics updated successfully
2025-04-16T18:24:16.304515+0300 ERROR Create error: Traceback (most recent call last):
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 545, in _prepare_and_execute
    self._rows = deque(await prepared_stmt.fetch(*parameters))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/asyncpg/prepared_stmt.py", line 267, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/asyncpg/prepared_stmt.py", line 256, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 206, in bind_execute
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "patients_fio_key"
DETAIL:  Key (fio)=(Мельников Сергей Владимирович) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "patients_fio_key"
DETAIL:  Key (fio)=(Мельников Сергей Владимирович) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/src/routing/base.py", line 120, in create
    obj = await service.create_object(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/src/services/base.py", line 14, in create_object
    return await self.repository.create(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/src/db/db.py", line 50, in wrapper
    raise e
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/src/db/db.py", line 47, in wrapper
    return await method(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/src/repositories/base.py", line 58, in create
    await session.commit()
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 1011, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/slsforme/Programming/python/fastapi/priroda_razuma/env/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "patients_fio_key"
DETAIL:  Key (fio)=(Мельников Сергей Владимирович) already exists.
[SQL: INSERT INTO patients (fio, age) VALUES ($1::VARCHAR, $2::INTEGER) RETURNING patients.id, patients.created_at, patients.updated_at]
[parameters: ('Мельников Сергей Владимирович', 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

2025-04-16T18:29:14.650273+0300 INFO Metrics updated successfully
2025-04-16T18:34:14.688161+0300 INFO Metrics updated successfully
2025-04-16T18:39:14.701769+0300 INFO Metrics updated successfully
2025-04-16T18:42:20.790609+0300 INFO Metrics updated successfully
2025-04-16T18:47:20.799396+0300 INFO Metrics updated successfully
2025-04-16T18:52:20.816602+0300 INFO Metrics updated successfully
2025-04-16T18:57:20.853597+0300 INFO Metrics updated successfully
2025-04-16T19:02:20.863417+0300 INFO Metrics updated successfully
2025-04-16T19:07:20.890905+0300 INFO Metrics updated successfully
2025-04-16T19:12:20.925963+0300 INFO Metrics updated successfully
2025-04-16T19:17:20.957961+0300 INFO Metrics updated successfully
2025-04-16T19:22:20.983111+0300 INFO Metrics updated successfully
2025-04-16T19:27:21.010468+0300 INFO Metrics updated successfully
2025-04-16T19:32:21.020118+0300 INFO Metrics updated successfully
2025-04-16T19:37:21.043438+0300 INFO Metrics updated successfully
2025-04-17T00:24:42.603468+0300 INFO Metrics updated successfully
2025-04-17T00:29:42.612214+0300 INFO Metrics updated successfully
2025-04-17T00:34:42.640734+0300 INFO Metrics updated successfully
2025-04-17T00:39:42.675444+0300 INFO Metrics updated successfully
2025-04-17T00:44:42.703430+0300 INFO Metrics updated successfully
2025-04-17T00:49:42.715695+0300 INFO Metrics updated successfully
2025-04-17T00:54:42.743925+0300 INFO Metrics updated successfully
2025-04-17T00:59:42.756395+0300 INFO Metrics updated successfully
2025-04-17T01:04:42.783107+0300 INFO Metrics updated successfully
2025-04-17T01:09:42.793146+0300 INFO Metrics updated successfully
2025-04-17T01:14:42.810124+0300 INFO Metrics updated successfully
2025-04-17T01:19:42.838773+0300 INFO Metrics updated successfully
2025-04-17T01:24:42.867214+0300 INFO Metrics updated successfully
2025-04-17T01:29:42.894982+0300 INFO Metrics updated successfully
2025-04-17T01:34:42.903125+0300 INFO Metrics updated successfully
2025-04-17T01:39:42.912655+0300 INFO Metrics updated successfully
2025-04-17T01:44:42.923606+0300 INFO Metrics updated successfully
2025-04-17T01:49:42.931433+0300 INFO Metrics updated successfully
2025-04-17T01:54:42.941363+0300 INFO Metrics updated successfully
2025-04-17T01:59:42.961195+0300 INFO Metrics updated successfully
2025-04-17T02:04:42.988338+0300 INFO Metrics updated successfully
2025-04-17T02:09:43.018821+0300 INFO Metrics updated successfully
2025-04-17T02:14:43.026834+0300 INFO Metrics updated successfully
2025-04-17T02:19:43.048779+0300 INFO Metrics updated successfully
2025-04-17T02:24:43.076191+0300 INFO Metrics updated successfully
2025-04-17T02:29:43.094775+0300 INFO Metrics updated successfully
